# introduccion a numpy

In [1]:
import numpy as np

# Arrays
es una estructura de datos

In [10]:
# array cuyos numeros son todos 0
a=np.zeros((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
print(a.ndim)
print(a.shape)
print(a.size)


2
(3, 5)
15


describe el array
un ndim
un shape
un size

describe el array

In [7]:
#ejemplo 2
a=np.zeros((2,3,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [9]:
print(a.ndim)
print(a.shape)
print(a.size)

3
(2, 3, 4)
24
